apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuitemlisting-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MenuItemListing
  template:
    metadata:
      labels:
        app: MenuItemListing
    spec:
      containers:
      - name: menuitemlisting
        image:  crfirstapi.azurecr.io/firstcrrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: menuitemsn

---
apiVersion: v1
kind: Service
metadata:
  name: menuitemlisting
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MenuItemListing
